### PR TITLE
Add arecommuting

### PR DESCRIPTION
**Pull request by ssiccha**

### CODE REVIEW

**Review by fingolfin — APPROVED** [review]
Wonder if there is already existing code in recog which could use it...

**Comment by ssiccha** [comment]
Grepping `gap/` for `isone.*Comm` yields:

```
gap/SnAnBB.gi:30:        if not isone(ri)(Comm(s,t)^2) then
gap/SnAnBB.gi:1079:#                           if not(isone(ri)(Comm(c,c^b)))  then
gap/SnAnBB.gi:1086:#                                 if isone(ri)(Comm(y, y^(b^2))) then
gap/SnAnBB.gi:1093:#                             elif isone(ri)(Comm(c, c^(b^2))) then
gap/SnAnBB.gi:1097:#                                 if isone(ri)(Comm(y,y^b)) then
gap/SnAnBB.gi:1107:#                                 if isone(ri)(Comm(y,y^b)) then
gap/SnAnBB.gi:1110:#                                 elif isone(ri)(Comm(y,y^(b^2))) then
gap/SnAnBB.gi:1158:#                           if not(isone(ri)(Comm(c,c^b))) and
gap/SnAnBB.gi:1159:#                              not(isone(ri)(Comm(c,c^(b^2)))) and
gap/SnAnBB.gi:1160:#                              not(isone(ri)(Comm(c,c^(b^4)))) then
gap/projective/findnormal.gi:410:  if ForAll(GeneratorsOfGroup(G),g->isone(Comm(g,y))) then
```
I'll open a separate PR for that.

**Comment by ssiccha** [comment]
The calls of `Comm` above are commented out, except for the first and the last one. The first one only checks whether the commutator squares to the identity, the last one is in a function which handles `isone` differently from the rest of recog.

**Comment by wilfwilson** [comment]
I just want to mention that the present tense of 'are commuting' sounds weird, I think it'd basically only ever hear someone say "(if) g and h commute..." or "do g and h commute?" rather than "(if) g and h are commuting..." or "are g and h commuting?".

More natural sounding names IMO could be
```
commute
docommute
arecommutingelements
```
(where the 'commuting' in the final one in acting more like an adjective than a verb).

(Sorry for the bikeshedding, obviously not an important issue).

**Pull request merged**
