### PR TITLE
Add test for LargeBasePrimitive

### PR DESCRIPTION
**Pull request by ssiccha**
Adds test for LargeBasePrimitive.
~~Moves two broken sporadic test cases.~~

### CODE REVIEW

**Comment by ssiccha** [comment]
I removed the commit about the tests for sporadic group. If we merge #197, then we won't need that commit anymore.

**Review by fingolfin — CHANGES_REQUESTED** [review]
This look good, except that neither the file content nor its name indicate that this is supposed to be a test for `LargeBasePrimitive`. I suggest to rename the file to match, and/or to mention `LargeBasePrimitive` in a comment

**Comment by ssiccha** [comment]
The file is now called `PermLargeBasePrimitive.tst` and contains a comment. Also I changed the S_23 to be an S_19 which is quicker and also triggers `LargeBasePrimitive`.

**Comment by ssiccha** [comment]
The tests that fail are sporadic groups that aren't recognized correctly. So from my POV this can be merged in.

**Comment by ssiccha** [comment]
@fingolfin could you have a look again?

**Pull request merged**
